-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 29bf11d13689a0a9a895c41eb3591c7e942d377d
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: flake8
        args:
        - --max-line-length=79
        - --exclude=*/migrations/*,docs/*
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
        args:
        - requirements-dev.txt
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    sha: 67c970e89857fdcebcd59ace94950a3331985a3b
    hooks:
    -   id: pep257
        args:
        - --explain
        - --ignore=D100,D101,D102,D103,D104,D105,D203
-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 934072fb29303aaa64bead610be042049e9db488
    hooks:
    -   id: python-import-sorter
